### ISSUE TITLE
OpenSSL Certificate and PrivateKey text load error

### ISSUE THREAD

**Issue by Atom-Soft** [geby/synapse#12]
Hello, 

I try ssl server and client with TTCPBlockSocket 2-ways.
- make cert and privkey file used openssl.
1) Sample with cert and privkey file is perfect working.
    SSLSock.SSL.CertificateFile := 'certfile';
    SSLSock.SSL.PrivateKeyFile := 'privkeyfile';
    SSLSock.Socket := vSocket;
    SSLSock.SSLAcceptConnection;
    ....
    (Working good)
2) Sample with cert and privkey text is error. message is "asn1 encoding routine::wrong tag
   SSLSock.SSL.Certificate := 'cert-text';
    SSLSock.SSL.PrivateKey := 'privkey-text';
    SSLSock.Socket := vSocket;
    SSLSock.SSLAcceptConnection;

'cert-text' --> -----BEGIN CERTIFICATE-----#13#10MII.....
Actually cert-text is certfile data. same text.

I try get text from cert and privkey file like this. (This function working well with Delphi Cross Socket)

```
function GetCertificateData(const ACertFile, AKeyFile: string; var ACertificate, APrivateKey: string): Boolean;
  function GetFullText(ALines: TArray<string>): string;
  var
    i                           : Integer;
    vLine                       : string;
  begin
    Result                      := ALines[0];
    for i := 1 to Length(ALines) - 1 do
      Result                      := Result + #13#10 + ALines[i];
  end;
var
  vLines                      : TArray<string>;
begin
  Result                      := True;

  ACertificate                := '';
  APrivateKey                 := '';

  if TFile.Exists(ACertFile) then
    ACertificate                := GetFullText(TFile.ReadAllLines(ACertFile));
  if TFile.Exists(AKeyFile) then
    APrivateKey                 := GetFullText(TFile.ReadAllLines(AKeyFile));

  if (ACertificate = '') or (APrivateKey = '') then
    Result                      := False;
end; 
```

This code for 'cert-text' and 'privkey-text'

**Comment by rvk01** [comment]
> 2\. Sample with cert and privkey text is error. message is "asn1 encoding routine::wrong tag
>     SSLSock.SSL.CertificateFile := 'cert-text';
>     SSLSock.SSL.PrivateKeyFile := 'privkey-text';

So why are you using CertificateFile for passing the certificate as string?
That's what Certificate and PrivateKey are for. The "File" version should only be for a file.

    {:Used for loading certificate from disk file. See to plugin documentation
     if this method is supported and how!}
    property CertificateFile: string read FCertificateFile write FCertificateFile;

```
    {:Used for loading private key from disk file. See to plugin documentation
     if this method is supported and how!}
    property PrivateKeyFile: string read FPrivateKeyFile write FPrivateKeyFile;

    {:Used for loading certificate from binary string. See to plugin documentation
     if this method is supported and how!}
    property Certificate: Ansistring read FCertificate write FCertificate;

    {:Used for loading private key from binary string. See to plugin documentation
     if this method is supported and how!}
    property PrivateKey: Ansistring read FPrivateKey write FPrivateKey;

```

**Comment by Atom-Soft** [comment]
Ooops!!!

sorry for mistake my sample code.

Sample with cert and privkey text is error. message is "asn1 encoding routine::wrong tag
SSLSock.SSL.Certificate := 'cert-text';
SSLSock.SSL.PrivateKey := 'privkey-text';
SSLSock.Socket := vSocket;
SSLSock.SSLAcceptConnection;

I tried this code. Sorry. 
I'll fixed code.

Thank you.

**Comment by Atom-Soft** [comment]
> Ooops!!!
> 
> sorry for mistake my sample code.
> 
> Sample with cert and privkey text is error. message is "asn1 encoding routine::wrong tag SSLSock.SSL.Certificate := 'cert-text'; SSLSock.SSL.PrivateKey := 'privkey-text'; SSLSock.Socket := vSocket; SSLSock.SSLAcceptConnection;
> 
> I tried this code. Sorry. I'll fixed code.
> 
> Thank you.



> > 2. Sample with cert and privkey text is error. message is "asn1 encoding routine::wrong tag
> > SSLSock.SSL.CertificateFile := 'cert-text';
> > SSLSock.SSL.PrivateKeyFile := 'privkey-text';
> 
> So why are you using CertificateFile for passing the certificate as string? That's what Certificate and PrivateKey are for. The "File" version should only be for a file.
> 
> ```
>     {:Used for loading certificate from disk file. See to plugin documentation
>      if this method is supported and how!}
>     property CertificateFile: string read FCertificateFile write FCertificateFile;
> 
>     {:Used for loading private key from disk file. See to plugin documentation
>      if this method is supported and how!}
>     property PrivateKeyFile: string read FPrivateKeyFile write FPrivateKeyFile;
> 
>     {:Used for loading certificate from binary string. See to plugin documentation
>      if this method is supported and how!}
>     property Certificate: Ansistring read FCertificate write FCertificate;
> 
>     {:Used for loading private key from binary string. See to plugin documentation
>      if this method is supported and how!}
>     property PrivateKey: Ansistring read FPrivateKey write FPrivateKey;
> ```

Ooops!!!

sorry for mistake my sample code.

Sample with cert and privkey text is error. message is "asn1 encoding routine::wrong tag
```
SSLSock.SSL.Certificate := 'cert-text';
SSLSock.SSL.PrivateKey := 'privkey-text';
SSLSock.Socket := vSocket;
SSLSock.SSLAcceptConnection;
```

I tried this code. Sorry.
I'll fixed code.

Thank you.

**Comment by Atom-Soft** [comment]
> > Sample with cert and privkey text is error. message is "asn1 encoding routine::wrong tag
> 
> Yes. But the documentation also states clearly for "ASN1 DER format only", not PEM. http://synapse.ararat.cz/doc/help/blcksock.TCustomSSL.html
> 
> So you need to convert your PEM format to ASN1 DER. You could try this by doing it manually with `openssl x509 -inform PEM -outform DER -in server.pem -out server.der`
> 
> There are some other options from this post onwards: https://forum.lazarus.freepascal.org/index.php?topic=59289.msg442075#msg442075

Oh! thank you.

I didn't check comment area.
ASN1 DER format only. 
Thank you for your tip!!!

Have a nice day.
;)
